config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('seller.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from .views import BooksView, CreateBookView, delete_book, EditBookView

app_name = 'seller'

urlpatterns = [
    path('books/', BooksView.as_view(), name='books'),
    path('add-book/', CreateBookView.as_view(), name='add_book'),
    path('delete-book/<int:product_id>/', delete_book, name='delete_book'),
    path('edit-book/<int:product_id>/', EditBookView.as_view(), name='edit_book'),
]

users/urls.py
from django.urls import path
from .views import HomeView, ProductDetailView, CartDeteailView, delete_from_cart, CategoryView, LoginView, RegisterView, LogoutView, Profile, EditProfileView, AdminDashboardView, UsersView, UsersEditView, BooksView, delete_users

app_name = 'users'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<int:product_id>/', ProductDetailView.as_view(), name='detail'),
    path('delete/<int:product_id>/', delete_from_cart, name='delete'),
    path('cart-detail/', CartDeteailView.as_view(), name='cart_detail'),
    path('category/<int:id>/', CategoryView.as_view(), name='category'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', Profile.as_view(), name='profile'),
    path('edit-profile/<int:id>/', EditProfileView.as_view(), name='edit_profile'),
    path('admin-dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('users/', UsersView.as_view(), name='users'),
    path('edit-users/<int:id>/', UsersEditView.as_view(), name='edit_users'),
    path('books/', BooksView.as_view(), name='books'),
    path('delete-users/<int:id>/', delete_users, name='delete_users'),
]

seller/models.py
from django.db import models

# Create your models here.

seller/forms.py
from django import forms
from users.models import Product





class AddBookForm(forms.ModelForm):
    class Meta:
        model = Product 
        fields = ['name', 'price', 'quantity', 'description', 'image', 'category']  
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }
        

seller/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from users.permissions import SellerRequiredMixin
from users.models import Product
from .forms import AddBookForm



class BooksView(SellerRequiredMixin, View):
    def get(self, request):
        books = Product.objects.all()
        return render(request, 'seller/books.html', context={"books":books})
    
class CreateBookView(SellerRequiredMixin, View):
    def get(self, request):
        form = AddBookForm()
        return render(request, 'seller/add_book.html', context={"form":form})
    
    def post(self, request):
        form = AddBookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users:home')
        return render(request, 'seller/add_book.html', {'form': form})
    
def delete_book(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.delete()
    return redirect('users:home')


class EditBookView(SellerRequiredMixin, View):
    def get(self, request, product_id):
        book = get_object_or_404(Product, id=product_id)
        form = AddBookForm(instance=book)
        return render(request, 'seller/add_book.html', {'form': form})
    
    def post(self, request, product_id):
        book = get_object_or_404(Product, id=product_id)
        form = AddBookForm(instance=book)
        if request.method == 'POST':
            form = AddBookForm(request.POST, request.FILES, instance=book)  
            if form.is_valid():
                form.save()
                return redirect('users:home')

        return render(request, 'seller/add_book.html', context={'form':form})

seller/templates/seller/add_book.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html>
<body> 
    <div class="container mt-4" style="background-color: rgb(255, 255, 252);">

        <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit" class="btn btn-success mt-4 mb-5">Save</button>
        </form>
        </div>
</body>
</html>


{% endblock content %}

seller/templates/seller/books.html
{% extends 'seller/seller_dashboard.html' %}

{% block content %}
<div>
    <a href="{% url 'seller:add_book' %}">Add Book</a>
</div>
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Buttun</th>
      </tr>
    </thead>
    <tbody>
        {% for book in books %}
      <tr>
        <th scope="row">{{book.id}}</th>
        <td>{{book.name}}</td>
        <td>{{book.price}}</td>
        <td>{{book.quantity}}</td>
        <td><a class="btn btn-outline-warning" href="">edit</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

seller/templates/seller/seller_dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seller</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.min.css"
    rel="stylesheet"
    />
</head>
<body style="background-color: rgb(234, 245, 245);">
    <!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="background-color: rgb(214, 213, 208);">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a
            href=""
            class="list-group-item list-group-item-action py-2 ripple"
            aria-current="true"
          >
          <i class="fas fa-globe fa-fw me-3"></i><span>Bosh sahifa</span>
          </a>
          
          <a href="{% url 'seller:books' %}" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-users fa-fw me-3"></i><span>Kitoblar</span></a
          >
          <a href="" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-bar fa-fw me-3"></i><span>Sozlamalar</span></a
          >
        </div>
      </div>
    </nav>
    <!-- Sidebar -->
  
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button data-mdb-button-init
          class="navbar-toggler"
          type="button"
          data-mdb-collapse-init
          data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
  
        <!-- Brand -->
        <a class="navbar-brand" href="#">
        <i class="fa-solid fa-book-open-reader"></i>&nbsp;Sotuvchi</a>
      </a>
  
        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">

          <!-- Avatar -->
          <li class="nav-item dropdown">
            <a
              data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="{{user.image.url}}"
                class="rounded-circle"
                height="22"
                alt="Avatar"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <li>
                <a class="dropdown-item" href="{% url 'users:profile' %}">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->
  
  <!--Main layout-->
  <main style="margin-top: 58px;">
    <div class="container pt-4">
        {% block content %}

        {% endblock content %}
    </div>
  </main>
  <!--Main layout-->
</body>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.umd.min.js"
></script>
</html>