config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('seller.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from .views import BooksView, CreateBookView, delete_book, EditBookView

app_name = 'seller'

urlpatterns = [
    path('books/', BooksView.as_view(), name='books'),
    path('add-book/', CreateBookView.as_view(), name='add_book'),
    path('delete-book/<int:product_id>/', delete_book, name='delete_book'),
    path('edit-book/<int:product_id>/', EditBookView.as_view(), name='edit_book'),
]

users/urls.py
from django.urls import path
from .views import HomeView, ProductDetailView, CartDeteailView, delete_from_cart, CategoryView, LoginView, RegisterView, LogoutView, Profile, EditProfileView, AdminDashboardView, UsersView, UsersEditView, BooksView, delete_users

app_name = 'users'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<int:product_id>/', ProductDetailView.as_view(), name='detail'),
    path('delete/<int:product_id>/', delete_from_cart, name='delete'),
    path('cart-detail/', CartDeteailView.as_view(), name='cart_detail'),
    path('category/<int:id>/', CategoryView.as_view(), name='category'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', Profile.as_view(), name='profile'),
    path('edit-profile/<int:id>/', EditProfileView.as_view(), name='edit_profile'),
    path('admin-dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('users/', UsersView.as_view(), name='users'),
    path('edit-users/<int:id>/', UsersEditView.as_view(), name='edit_users'),
    path('books/', BooksView.as_view(), name='books'),
    path('delete-users/<int:id>/', delete_users, name='delete_users'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    USER_ROLE =(
        ('client','client'),
        ('seller','seller'),
        ('admin','admin'),
    )
    image = models.ImageField(upload_to='profile_pics/', blank=True, null=True, default='profile_pics/default.jpg')
    phone_number = models.CharField(max_length=13, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    jobs = models.CharField(max_length=200, blank=True, null=True)
    user_role = models.CharField(max_length=100,choices=USER_ROLE,default="client")

    def str(self):
        return self.first_name
    

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='product_image', null=True, blank=True)
    in_stock = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')

    def __str__(self):
        return self.name
    
    @property
    def total_price(self):
        return self.price * self.quantity
    

class Cart(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()


    def __str__(self):
        return self.product.name


class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client')
    image = models.ImageField(upload_to='client_image', null=True, blank=True)

    def __str__(self) -> str:
        return self.user.first_name
    

class Seller(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller')

    def __str__(self):
        return self.user.first_name

users/forms.py
from django import forms
from .models import User



class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Username"}))
    password = forms.CharField(widget=forms.PasswordInput({"class": "form-control", "placeholder": "Password"}))


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Name"}))
    phone_number = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Phone Number"}))
    first_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "First Name"}))
    last_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Last Name"}))

    password = forms.CharField(widget=forms.PasswordInput({"class": "form-control", "placeholder": "Password"}))
    confirm_password = forms.CharField(widget=forms.PasswordInput({"class": "form-control", "placeholder": "Confirm Password"}))

    class Meta:
        model = User
        fields = ('username', 'phone_number', 'first_name', 'last_name', 'password', 'confirm_password')

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return password
    
class ProfileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Name"}))
    phone_number = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Phone Number"}))
    first_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "First Name"}))
    last_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Last Name"}))
    jobs = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Jobs"}))
    address = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "address"}))
    email = forms.CharField(widget=forms.EmailInput({"class": "form-control", "placeholder": "address"}))
    image = forms.ImageField(widget=forms.FileInput({"class": "form-control", "placeholder": "image"}))
    
    class Meta:
        model = User
        fields = ('username', 'phone_number','address', 'first_name', 'last_name','image','email','jobs')


class UsersEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Name"}))
    phone_number = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Phone Number"}))
    first_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "First Name"}))
    last_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Last Name"}))
    jobs = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Jobs"}))
    address = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "address"}))
    email = forms.CharField(widget=forms.EmailInput({"class": "form-control", "placeholder": "address"}))
    image = forms.ImageField(widget=forms.FileInput({"class": "form-control", "placeholder": "image"}))

    class Meta:
        model = User
        fields = ('username', 'phone_number','address', 'first_name', 'last_name','image','email','jobs', 'user_role')

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Cart, Category, Client, User, Seller
from .forms import LoginForm, RegisterForm, ProfileForm, UsersEditForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .permissions import AdminRequiredMixin

class HomeView(View):
    def get(self, request):
        products = Product.objects.filter(in_stock=True)
        cart = Cart.objects.count()
        categories = Category.objects.all()
        products = Product.objects.all()
        return render(request, 'users/home.html', context={"products":products, "cart":cart, "categories":categories})
    
class CategoryView(View):
    def get(self, request, id):
        category = get_object_or_404(Category, id=id)
        products = category.product.all()
        categories = Category.objects.all()
        return render(request, 'users/home.html', context={"products":products, "categories":categories})

class ProductDetailView(View):
    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        cart = Cart.objects.count()
        return render(request, 'users/detail.html', context={"product":product, "cart":cart})
    

    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        quantity = int(request.POST['cart'])
        if Cart.objects.filter(product=product).exists():
            cart = Cart.objects.filter(product=product).first()
            cart.quantity += quantity
            cart.save()
        else:
            cart = Cart()
            cart.product = product
            cart.quantity = quantity
            cart.save()
        return redirect('users:home')
    
class CartDeteailView(View):
    def get(self, request):
        products = Cart.objects.all()
        return render(request, 'users/cart_detail.html', context={"products":products})
    

def delete_from_cart(request, product_id):
    cart = get_object_or_404(Cart, id=product_id)
    cart.delete()
    return redirect('users:home')


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'users/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.user_role == 'admin':
                    return redirect('users:home')
                elif user.user_role == 'client':
                    return redirect('users:home')
                elif user.user_role == 'seller':
                    return redirect('users:home')
        

class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            if user.user_role == 'client':
                new_client = Client()
                new_client.user = user
                new_client.save()

            return redirect('/')
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})
    
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/')


class Profile(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profile.html')
    

class EditProfileView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(instance=user)
        return render(request, 'users/edit_profile.html', {'form': form})

    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('/') 
        return render(request, 'users/edit_profile.html', {'form': form})
    
class AdminDashboardView(AdminRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/admin_dashboard.html')
    
class UsersView(View):
    def get(self, request):
        users = User.objects.all()
        return render(request, 'users/users.html', context={"users":users})
    
class UsersEditView(AdminRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = UsersEditForm(instance=user)
        return render(request, 'users/edit_users.html', {'form': form})
    
    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = UsersEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:users') 
        return render(request, 'users/edit_users.html', {'form': form})
    

class BooksView(View):
    def get(self, request):
        books = Product.objects.all()
        return render(request, 'users/books.html', context={"books":books})
    
def delete_users(request, id):
    user = get_object_or_404(User, id=id)
    user.delete()
    return redirect('users:users')

users/templates/users/admin_dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Admin Panel</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.min.css"
    rel="stylesheet"
    />
</head>
<body style="background-color: rgb(234, 245, 245);">
    <!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="background-color: rgb(214, 213, 208);">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a
            href="{% url 'users:users' %}"
            class="list-group-item list-group-item-action py-2 ripple"
            aria-current="true"
          >
          <i class="fas fa-globe fa-fw me-3"></i><span>Bosh sahifa</span>
          </a>
          
          <a href="{% url 'users:books' %}" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-users fa-fw me-3"></i><span>Books</span></a
          >
          <a href="" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-bar fa-fw me-3"></i><span>Sozlamalar</span></a
          >
        </div>
      </div>
    </nav>
    <!-- Sidebar -->
  
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button data-mdb-button-init
          class="navbar-toggler"
          type="button"
          data-mdb-collapse-init
          data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
  
        <!-- Brand -->
        <a class="navbar-brand" href="#">
        <i class="fa-solid fa-book-open-reader"></i>&nbsp;Admin</a>
      </a>
  
        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">

          <!-- Avatar -->
          <li class="nav-item dropdown">
            <a
              data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="{{user.image.url}}"
                class="rounded-circle"
                height="22"
                alt="Avatar"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <li>
                <a class="dropdown-item" href="{% url 'users:profile' %}">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->
  
  <!--Main layout-->
  <main style="margin-top: 58px;">
    <div class="container pt-4">
        {% block content %}

        {% endblock content %}
    </div>
  </main>
  <!--Main layout-->
</body>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.umd.min.js"
></script>
</html>

users/templates/users/books.html
{% extends 'users/admin_dashboard.html' %}

{% block content %}


<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Turi</th>
      </tr>
    </thead>
    <tbody>
        {% for book in books %}
      <tr>
        <th scope="row">{{book.id}}</th>
        <td>{{book.name}}</td>
        <td>{{book.price}}</td>
        <td>{{book.quantity}}</td>
        <td>{{book.category}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

users/templates/users/cart_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for cart in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{cart.product.image.url}}" alt="..." width="150" height="250" />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{cart.product.name}}</h5>
                            <!-- Product price-->
                            Quantity: {{cart.quantity}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-danger mt-auto" href="{% url 'users:delete' cart.id %}">Remove from cart</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/detail.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{product.image.url}}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: BST-498</div>
                <h1 class="display-5 fw-bolder">{{product.name}}</h1>
                <div class="fs-5 mb-5">
                    
                    <span>${{product.price}}</span>
                </div>
                <p class="lead">{{product.description}}</p>
                <div class="d-flex">
                    {% if user.user_role == 'client' %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <input class="form-control text-center me-3" id="inputQuantity" name="cart" type="num" value="1" style="max-width: 3rem" />
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                        </button>
                    </form>
                    {% endif %}
                    {% if user.user_role == 'seller' %}
                    <div ><a class="btn btn-outline-danger" href="{% url 'seller:delete_book' product.id %}">Remove</a>
                        <a class="btn btn-outline-warning" href="{% url 'seller:edit_book' product.id %}">Update</a></div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/edit_profile.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4 mb-10" style="background-color: rgb(238, 232, 185);">

<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-success mt-2 mb-4">Save</button>
</form>
</div>

{% endblock content %}

users/templates/users/edit_users.html
{% extends 'users/admin_dashboard.html' %}

{% block content %}

<div class="container mt-4 mb-10" style="background-color: rgb(224, 221, 197);">

<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-success mt-2 mb-4">Save</button>
</form>
</div>

{% endblock content %}

users/templates/users/home.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{product.image.url}}" alt="..." width="150" height="250"/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{product.name}}</h5>
                            <!-- Product price-->
                            ${{product.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'users:detail' product.id %}">Batafsil</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body>
        <div class="login-container">
            <h2>Login</h2>
            <form id="login-form" method="post">
                {% csrf_token %}
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
    
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
    
                <button type="submit">Login</button>
            </form>
        </div>

    <script src="script.js"></script>
</body>
</html>

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

<section>
    <div class="container py-5">
      <div class="row">
        <div class="col">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{user.first_name}} {{user.last_name}}</h5>
              <p class="text-muted mb-1">Python developer</p>
              <p class="text-muted mb-4">{{user.address}}</p>
              <div class="d-flex justify-content-center mb-2">
                <a href="" class="btn btn-primary">Reset password</a>
                <a href="{% url 'users:edit_profile' user.id %}" class="btn btn-outline-primary ms-1">Edit</a>
              </div>
            </div>
          </div>
                  
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone_number}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone_number}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.address}}</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html>
<body> 
	<!--register-starts-->
    <div class="container mt-4" style="background-color: rgb(255, 255, 252);">

        <form  method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-success mt-4 mb-5">Register</button>
        </form>
        </div>
    
	<!--register-end-->


</body>
</html>


{% endblock content %}

users/templates/users/users.html
{% extends 'users/admin_dashboard.html' %}

{% block content %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Role</th>
        <th scope="col">Job</th>
        <th scope="col">Buttuns</th>
      </tr>
    </thead>
    <tbody>
        {% for user in users %}
      <tr>
        <th scope="row">{{user.id}}</th>
        <td>{{user.first_name}}</td>
        <td>{{user.user_role}}</td>
        <td>{{user.jobs}}</td>
        <td><a class="btn btn-outline-warning" href="{% url 'users:edit_users' user.id %}">edit</a>
          <a class="btn btn-outline-danger" href="{% url 'users:delete_users' user.id %}">Delete</a></td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}